/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;


import MODEL.Discharged;
import MODEL.Transfered;
import SERVICE.DischargedInterface;
import SERVICE.InpatientInterface;
import SERVICE.TransferedInterface;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author destin
 */
public class PatientHistory_admin extends javax.swing.JFrame {
DefaultTableModel tableModel = new DefaultTableModel(); // discharge table
DefaultTableModel tModel = new DefaultTableModel();  // for transfer table
    /**
     * Creates new form PatientTransfer
     */
    public PatientHistory_admin() {
        initComponents();
        AddTableColumnDischarged();
        AddTableColumnTransfered();
        AddTableRowDischarged();
        AddTableRowTransfered();
        
    }
    
    public void AddTableColumnDischarged()
            
    {
        tableModel.addColumn("Id");
        tableModel.addColumn("National id");
        tableModel.addColumn("Name");
        tableModel.addColumn("Date of birth");
        tableModel.addColumn("Sickness");
        tableModel.addColumn("Paid");
        tableModel.addColumn("Department");
        tableModel.addColumn("Room");
        tableModel.addColumn("phone no");
        tableModel.addColumn("Date in");
        
        OutpatienceTable.setModel(tableModel);
        
    }
     public void AddTableColumnTransfered()
            
    {
        tModel.addColumn("Id");
        tModel.addColumn("National id");
        tModel.addColumn("Name");
        tModel.addColumn("Date of birth");
        tModel.addColumn("Sickness");
        tModel.addColumn("Paid");
        tModel.addColumn("Department");
        tModel.addColumn("Room");
        tModel.addColumn("phone no");
        tModel.addColumn("Date in");
        
        TransferedTable.setModel(tModel);
        
    }
        public void AddTableRowDischarged()
    {
       
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",6000);
            DischargedInterface intf = (DischargedInterface) registry.lookup("discharge");

            List<Discharged> inp = intf.allDischarged();
            String department = null;
            String room =null;
            for (Discharged obj : inp) {
            if (obj.getDepartment() != null || obj.getRoom() != null) {
                department = obj.getDepartment() != null ? obj.getDepartment().getDep_name() : "";
                room = obj.getRoom() != null ? obj.getRoom().getRoom_no() : "";
            } else {
                department = "";
                room = "";
            }
            tableModel.addRow(new Object[]{
                obj.getId(),
                obj.getPatient_national_id(),
                obj.getInpatient_name(),
                obj.getDate_of_birth(),
                obj.getInpatient_sickness(),
                obj.getInpatient_amount_paid(),
                department,
                room,
                obj.getInpatient_phone_number(),
                obj.getInpatient_date_in(),
            });
        }
        }
        catch(Exception e)
        {
           e.printStackTrace();
            
        }
        
      
        }
        
     public void AddTableRowTransfered()
    {
       
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",6000);
           TransferedInterface intf = (TransferedInterface) registry.lookup("transfered");

            List<Transfered> inp = intf.allTransfered();
            String department = null;
            String room =null;
            for (Transfered obj : inp) {
            if (obj.getDepartment() != null || obj.getRoom() != null) {
                department = obj.getDepartment() != null ? obj.getDepartment().getDep_name() : "";
                room = obj.getRoom() != null ? obj.getRoom().getRoom_no() : "";
            } else {
                department = "";
                room = "";
            }
            tModel.addRow(new Object[]{
                obj.getId(),
                obj.getPatient_national_id(),
                obj.getInpatient_name(),
                obj.getDate_of_birth(),
                obj.getInpatient_sickness(),
                obj.getInpatient_amount_paid(),
                department,
                room,
                obj.getInpatient_phone_number(),
                obj.getInpatient_date_in(),
            });
        }
        }
        catch(Exception e)
        {
           e.printStackTrace();
            
        }
        
      
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutpatienceTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Logoutbtn = new javax.swing.JButton();
        Gobackbtn = new javax.swing.JButton();
        Searchdischarged = new javax.swing.JButton();
        seaarchTransferBtn = new javax.swing.JButton();
        SearchdischargedInp = new javax.swing.JTextField();
        SearchTransferInp = new javax.swing.JTextField();
        jScrollBar3 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        TransferedTable = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel1.setText("Patient History");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(117, 216, 158));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        OutpatienceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(OutpatienceTable);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Logoutbtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Logoutbtn.setIcon(new javax.swing.ImageIcon("/home/destin/Pictures/Project_Images/ICONS/logout.resized.png")); // NOI18N
        Logoutbtn.setText("LOG-OUT");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        Gobackbtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Gobackbtn.setIcon(new javax.swing.ImageIcon("/home/destin/Pictures/Project_Images/ICONS/back.resized.png")); // NOI18N
        Gobackbtn.setText("GO BACK");
        Gobackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobackbtnActionPerformed(evt);
            }
        });

        Searchdischarged.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Searchdischarged.setText("SEARCH");
        Searchdischarged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchdischargedActionPerformed(evt);
            }
        });

        seaarchTransferBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        seaarchTransferBtn.setText("SEARCH");
        seaarchTransferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaarchTransferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gobackbtn)
                        .addGap(62, 62, 62)
                        .addComponent(Logoutbtn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(SearchdischargedInp, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Searchdischarged, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchTransferInp, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(seaarchTransferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seaarchTransferBtn)
                    .addComponent(Searchdischarged, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchdischargedInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTransferInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gobackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        TransferedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TransferedTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Yrsa Light", 1, 14)); // NOI18N
        jLabel2.setText("Outpatiences");

        jLabel3.setFont(new java.awt.Font("Yrsa", 0, 18)); // NOI18N
        jLabel3.setText("Transfered Elsewhere");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage loginPage = new LoginPage();
        loginPage.show();
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void GobackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobackbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminHomePage admin = new AdminHomePage();
        admin.show();
    }//GEN-LAST:event_GobackbtnActionPerformed

    private void SearchdischargedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchdischargedActionPerformed
      try{
         Registry registry = LocateRegistry.getRegistry("127.0.0.1", 6000);
         DischargedInterface intf = (DischargedInterface) registry.lookup("transfered");

        Discharged searchCriteria = new Discharged();
        searchCriteria.setPatient_national_id(SearchdischargedInp.getText());
        Discharged obj = intf.getdischargedById(searchCriteria);
   
        if(obj!=null)
        {
          tableModel.setRowCount(0);
           tableModel.addRow(new Object[]{
                obj.getId(),
                obj.getPatient_national_id(),
                obj.getInpatient_name(),
                obj.getDate_of_birth(),
                obj.getInpatient_sickness(),
                obj.getInpatient_amount_paid(),
                obj.getDepartment().getDep_name(),
                obj.getRoom().getRoom_no(),
                obj.getInpatient_phone_number(),
                obj.getInpatient_date_in(),
            }); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, "User not found");
        }
      }
      catch(Exception e)
      {
          e.printStackTrace();
      }
    }//GEN-LAST:event_SearchdischargedActionPerformed

    private void seaarchTransferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaarchTransferBtnActionPerformed
        try{
         Registry registry = LocateRegistry.getRegistry("127.0.0.1", 6000);
         TransferedInterface intf = (TransferedInterface) registry.lookup("transfered");

        Transfered searchCriteria = new Transfered();
        searchCriteria.setPatient_national_id(SearchTransferInp.getText());
        Transfered obj = intf.gettransferedById(searchCriteria);
   
        if(obj!=null)
        {
          tModel.setRowCount(0);
           tModel.addRow(new Object[]{
                obj.getId(),
                obj.getPatient_national_id(),
                obj.getInpatient_name(),
                obj.getDate_of_birth(),
                obj.getInpatient_sickness(),
                obj.getInpatient_amount_paid(),
                obj.getDepartment().getDep_name(),
                obj.getRoom().getRoom_no(),
                obj.getInpatient_phone_number(),
                obj.getInpatient_date_in(),
            }); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, "User not found");
        }
      }
      catch(Exception e)
      {
          e.printStackTrace();
      }
    }//GEN-LAST:event_seaarchTransferBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHistory_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHistory_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHistory_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHistory_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientHistory_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gobackbtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JTable OutpatienceTable;
    private javax.swing.JTextField SearchTransferInp;
    private javax.swing.JButton Searchdischarged;
    private javax.swing.JTextField SearchdischargedInp;
    private javax.swing.JTable TransferedTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton seaarchTransferBtn;
    // End of variables declaration//GEN-END:variables
}
